name: Angular Unit Tests

on:
  pull_request: # This will make it run on all pull requests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # you can specify your desired Node.js version here

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test-ci
